/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness check that also requires the face model to be loaded.
         */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Guess a skin spec from a photo; the photo is read into memory and dropped.
         */
        post: operations["analyze_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Skin
         * @description Generate the skin PNG for a spec.
         */
        post: operations["render_skin_api_v1_skin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skin/normalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skin Normalize
         * @description Import a ready skin: 64x32 to 64x64 and model detection.
         */
        post: operations["skin_normalize_api_v1_skin_normalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papercraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Papercraft
         * @description Render the papercraft PDF for a 64x64 skin.
         */
        post: operations["papercraft_api_v1_papercraft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzeResponse
         * @description Spec guessed from a photo and warnings for the user.
         */
        AnalyzeResponse: {
            spec: components["schemas"]["SkinSpec"];
            /** Warnings */
            warnings: ("MULTIPLE_FACES" | "FACE_TOO_SMALL" | "LOW_LIGHT" | "HAIR_NOT_DETECTED" | "TORSO_NOT_VISIBLE" | "PALETTE_REDUCED" | "TRANSPARENT_BASE_PIXELS")[];
        };
        /** Body_analyze_api_v1_analyze_post */
        Body_analyze_api_v1_analyze_post: {
            /** Photo */
            photo: string;
            /**
             * Consent
             * @default
             */
            consent: string;
        };
        /** Body_papercraft_api_v1_papercraft_post */
        Body_papercraft_api_v1_papercraft_post: {
            /** Skin */
            skin: string;
            /**
             * Options
             * @description JSON-encoded PapercraftOptions
             */
            options: string;
        };
        /** Body_skin_normalize_api_v1_skin_normalize_post */
        Body_skin_normalize_api_v1_skin_normalize_post: {
            /** Skin */
            skin: string;
        };
        /**
         * ErrorBody
         * @description Error details.
         */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "CONSENT_REQUIRED" | "FILE_TOO_LARGE" | "UNSUPPORTED_FORMAT" | "IMAGE_TOO_SMALL" | "IMAGE_TOO_LARGE" | "NO_FACE" | "INVALID_SPEC" | "INVALID_SKIN" | "INVALID_OPTIONS" | "RATE_LIMITED" | "INTERNAL";
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /**
         * ErrorResponse
         * @description Uniform error envelope.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * HealthResponse
         * @description Liveness and model readiness.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * NormalizeResponse
         * @description Imported skin in 64x64 form.
         */
        NormalizeResponse: {
            /** Skin Png Base64 */
            skin_png_base64: string;
            /**
             * Model
             * @enum {string}
             */
            model: "classic" | "slim";
            /** Warnings */
            warnings: ("MULTIPLE_FACES" | "FACE_TOO_SMALL" | "LOW_LIGHT" | "HAIR_NOT_DETECTED" | "TORSO_NOT_VISIBLE" | "PALETTE_REDUCED" | "TRANSPARENT_BASE_PIXELS")[];
        };
        /**
         * Palette
         * @description Base color of every palette role.
         */
        Palette: {
            /** Skin */
            skin: string;
            /** Hair */
            hair: string;
            /** Eye White */
            eye_white: string;
            /** Iris */
            iris: string;
            /** Mouth */
            mouth: string;
            /** Shirt */
            shirt: string;
            /** Pants */
            pants: string;
            /** Shoes */
            shoes: string;
        };
        /**
         * SkinSpec
         * @description Everything needed to regenerate a skin; the client keeps it between calls.
         */
        SkinSpec: {
            /**
             * Spec Version
             * @default 1
             * @constant
             */
            spec_version: 1;
            /**
             * Model
             * @default classic
             * @enum {string}
             */
            model: "classic" | "slim";
            /**
             * Stylizer
             * @default template
             * @enum {string}
             */
            stylizer: "template" | "downsample";
            /**
             * Hair Style
             * @default short
             * @enum {string}
             */
            hair_style: "short" | "long" | "bald" | "fringe";
            palette: components["schemas"]["Palette"];
            /** Face Front */
            face_front?: string[][] | null;
        };
        /**
         * PapercraftOptions
         * @description Papercraft PDF options.
         */
        PapercraftOptions: {
            /**
             * Model
             * @default auto
             * @enum {string}
             */
            model: "classic" | "slim" | "auto";
            /**
             * Paper
             * @default A4
             * @enum {string}
             */
            paper: "A4" | "Letter";
            /**
             * Pixel Mm
             * @default 5
             */
            pixel_mm: number;
            /**
             * Mode
             * @default color
             * @enum {string}
             */
            mode: "color" | "numbered";
            /**
             * Flatten Overlay
             * @default true
             */
            flatten_overlay: boolean;
            /**
             * Grid Lines
             * @default true
             */
            grid_lines: boolean;
            /**
             * Lang
             * @default ru
             * @enum {string}
             */
            lang: "ru" | "en";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    analyze_api_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_v1_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    render_skin_api_v1_skin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkinSpec"];
            };
        };
        responses: {
            /** @description 64x64 RGBA skin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    skin_normalize_api_v1_skin_normalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_skin_normalize_api_v1_skin_normalize_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NormalizeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    papercraft_api_v1_papercraft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_papercraft_api_v1_papercraft_post"];
            };
        };
        responses: {
            /** @description Papercraft PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
